# CNOT Synthesis

In [1]:
import numpy as np

## STRUMOK CNOT Synthesis

In [2]:
# Reduction polynomial x^8 + x^4 + x^3 + x^2 + 1

# Reduction matrix
Q = np.array([
    [1, 0, 1, 1, 1, 0, 0, 0],
    [0, 1, 0, 1, 1, 1, 0, 0],
    [0, 0, 1, 0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0, 1, 1, 1],
    [1, 0, 1, 1, 0, 0, 1, 1],
    [1, 1, 1, 0, 0, 0, 0, 1],
    [1, 1, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
])

In [3]:
print(Q.transpose())

[[1 0 0 0 1 1 1 0]
 [0 1 0 0 0 1 1 0]
 [1 0 1 0 1 1 0 0]
 [1 1 0 1 1 0 0 0]
 [1 1 1 0 0 0 1 0]
 [0 1 1 1 0 0 0 0]
 [0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0]]


In [4]:
Qt = Q.copy().transpose()

In [5]:
Qt[2] = Qt[2] ^ Qt[0]
Qt[3] = Qt[3] ^ Qt[0]
Qt[4] = Qt[4] ^ Qt[0]

In [6]:
Qt[3] = Qt[3] ^ Qt[1]
Qt[4] = Qt[4] ^ Qt[1]
Qt[5] = Qt[5] ^ Qt[1]

In [7]:
Qt[4] = Qt[4] ^ Qt[2]
Qt[5] = Qt[5] ^ Qt[2]
Qt[6] = Qt[6] ^ Qt[2]

In [8]:
Qt[5] = Qt[5] ^ Qt[3]
Qt[6] = Qt[6] ^ Qt[3]
Qt[7] = Qt[7] ^ Qt[3]

In [9]:
Qt[6] = Qt[6] ^ Qt[4]
Qt[7] = Qt[7] ^ Qt[4]

In [10]:
Qt[7] = Qt[7] ^ Qt[5]

In [11]:
print(Qt)

[[1 0 0 0 1 1 1 0]
 [0 1 0 0 0 1 1 0]
 [0 0 1 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [12]:
Qtt = np.array(Qt).transpose()

In [13]:
print(Qtt)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 1 0 0 0 1 0 0]
 [1 1 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [14]:
Qtt[4] = Qtt[4] ^ Qtt[0]
Qtt[5] = Qtt[5] ^ Qtt[0]
Qtt[6] = Qtt[6] ^ Qtt[0]

In [15]:
Qtt[5] = Qtt[5] ^ Qtt[1]
Qtt[6] = Qtt[6] ^ Qtt[1]

In [16]:
Qtt[6] = Qtt[6] ^ Qtt[2]

In [17]:
print(Qtt)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]
